export const FETCH_POST_LINKS_REQUEST = 'FETCH_POST_LINKS_REQUEST';
export const FETCH_POST_LINKS_SUCCESS = 'FETCH_POST_LINKS_SUCCESS';
export const FETCH_POST_LINKS_ERROR = 'FETCH_POST_LINKS_ERROR';
export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';
export const AUTH_USER_REQUEST = 'AUTH_USER_REQUEST';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';